#!/sbin/openrc-run
# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="vaultwarden daemon"
description="Unofficial Bitwarden compatible server written in Rust"

command="/var/lib/vaultwarden/vaultwarden"
pidfile="/run/vaultwarden.pid"
start_stop_daemon_args="
	--env VW_CONFIG=${VW_CONFIG}
	--user ${VW_USER}
	--group ${VW_GROUP}
	--pidfile ${pidfile}
	--make-pidfile
	--background
"

depend() {
	need net
	use mysql postgresql
}
