#!/sbin/openrc-run
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="hydroxide daemon"
description="A third-party, open-source ProtonMail CardDAV, IMAP and SMTP bridge"

command="/usr/bin/hydroxide"
command_args="${HYDROXIDE_OPTS} ${HYDROXIDE_MODE}"

pidfile="/run/hydroxide.pid"
start_stop_daemon_args="--user ${USER} --pidfile ${pidfile} --make-pidfile --background"

depend() {
	need net
}
